fix conversion of bitmasks to strings
bluenviron/gomavlib pull request #81
Opened 2023-09-21 14:31 UTC by twpayne

Fixes #79.

This PR updates the code generator to generate correct bitmask to strings.

It also makes the generated strings deterministic. Before this PR, the order of labels within a string was random (it depended on map iteration order, which is non-deterministic). This PR ensures that all labels within a string are in the order of the bits in the bitmask.

It also adds some code to format the generated files with `go fmt`.

I've only regenerated the minimal dialect so you can see what effect the changes have without receiving a huge PR. If you're happy with this then I can regenerate the other dialects.

2023-09-21 20:00 UTC, aler9 requested changes
Thanks for this contribution, involving the bitmask flag definitely fixes the issue. I left a couple of code-related comments.

2023-09-22 12:10 UTC, twpayne commented on pkg/conversion/conversion.go
> +    }
Doh. Not sure why I included this. I've removed it.

2023-09-22 12:10 UTC, twpayne commented on pkg/conversion/conversion.go
> +
Done.

2023-09-22 12:10 UTC, twpayne commented
Thanks for the review. PR updated.

2023-09-23 09:33 UTC, merged